### ISSUE TITLE
Race condition on new language calling getNodeAtLocation 

### ISSUE THREAD

**Issue by AndreasArvidsson** [pokey/vscode-parse-tree#4]
The tree map is dependent on the events `onDidChangeVisibleTextEditors` and `onDidChangeTextDocument` to add new languages when needed.

Quickly changing language on a file or switching to a file with a different language and immediately calling `
getNodeAtLocation` throws an exception "Can't read property rootNode of undefined".

One solution would be that in getNodeAtLocation do the following:
* Check if a tree exists for the current document.
    - If true return result
* If false check if language is supported
    - If false throw a proper exception `Language {lang} is not supported by the tree parser`
* if true update the tree
* Return result

Similar thoughts might be applied to the function `getTree`

**Comment by pokey** [comment]
This approach seems reasonable, the only slight annoyance being that `getNodeAtLocation` would have to become async, because it might need to load the wasm, which is async.  Not sure I see a better alternative tho

**Comment by AndreasArvidsson** [comment]
I have no better solution. If you really want to keep it synchronous I guess you could always do a busy wait via a loop.

**Comment by pokey** [comment]
In #5, I opted to just raise a special exception ([`LanguageStillLoadingError`](https://github.com/pokey/vscode-parse-tree/blob/master/src/errors.ts#L10)) for this case.  Client code can catch the exception and try again.  If desired, I could add a separate version of the function that is async, but I think I'd prefer to keep the default implementation sync and just throw an exception
